// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package user

// Fill with you ideas below.

func GetUserById(id int64) (*Entity, error) {
	return Model.FindOne("id = ?", id)
}

func GetUserByName(username string) (*Entity, error) {
	return Model.FindOne("username = ?", username)
}
